version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres_docker
    environment: 
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - ./.volume_databases/postgres:/var/lib/postgresql/data
      - ./dump:/backup
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./init/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - 5432:5432
    networks:
      - exemplo-network

networks: 
  exemplo-network:
    driver: bridge
